# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_epaper
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

    # snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_epaper
  - board: nice_nano_v2
    shield: corne_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: corne_dongle
  - board: nice_nano_v2
    shield: corne_peripheral_left nice_view_adapter nice_epaper
  - board: nice_nano_v2
    shield: corne_peripheral_right nice_view_adapter nice_epaper
  # Settings reset builds
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: corne_dongle settings_reset
    artifact-name: corne_dongle-settings_reset-nice_nano_v2
  - board: nice_nano_v2
    shield: corne_peripheral_left settings_reset
    artifact-name: corne_peripheral_left-settings_reset-nice_nano_v2
  - board: nice_nano_v2
    shield: corne_peripheral_right settings_reset
    artifact-name: corne_peripheral_right-settings_reset-nice_nano_v2
